tidal-music/tidal-sdk-ios

- Scripts/landing.html
I thought it looked better if we corrected these :-)
> Fix typo: iOs -> iOS

- Scripts/combineDocumentation.sh
- Scripts/landing.html
After making the repo public, links in the deployed documentation pages failed due to changes in the relative paths.
This PR fixes it it by making the links absolute.
> Use absolute URLs in documentation links

- Sources/Auth/Auth.docc/Documentation.md
- Sources/Auth/README.md
- TestApps/Auth/AuthTestApp/AuthViewModel.swift
- Tests/AuthTests/ScopesTests.swift
The steps in the Auth `README` had some incorrect code snippets that needed to be fixed.
> Fix steps for ClientCredentials flow in Auth README

- .github/workflows/playlog-tests.yml
- .github/workflows/unit-test.yml
While we continue development of the PlayLog unit tests, we have moved them to a separate action that we can trigger manually.
Once they are completed and stable, we will decide the frequency on which to run them, given that they are inherently slow.
> Moved PlayLog tests to a separate GH Action

- .github/workflows/fossa-scan.yml
Otherwise this workflow blocks PRs from being merged.
> Add merge_group trigger to fossa scan

- .github/workflows/unit-test.yml
- Tests/PlayerTests/Helpers/XCTestCase+Player.swift
- Tests/PlayerTests/Player/PlaybackEngine/Internal/StreamingPrivileges/StreamingPrivilegesHandlerTests.swift
This PR improves speed and stability for StreamingPrivilegesHandlerTests by implementing a more efficient and flexible wait mechanism to allow the async tasks to do their work.
This is not fully controllable, but it has been proven to be quite reliable for us in other tests, and much better than waiting a set amount of time.
> Fix test flakiness in StreamingPrivilegesHandlerTests

- Sources/Player/Common/FeatureFlags/FeatureFlagProvider+Standard.swift
- Sources/Player/Common/FeatureFlags/FeatureFlagProvider.swift
- Sources/Player/Common/World/DevelopmentFeatureFlagProvider/DevelopmentFeatureFlagProvider+Live.swift
- Sources/Player/Common/World/DevelopmentFeatureFlagProvider/DevelopmentFeatureFlagProvider.swift
- Sources/Player/Mocks/Common/FeatureFlags/FeatureFlagProvider+Mock.swift
- Sources/Player/PlaybackEngine/Internal/PlayerItem.swift
- Sources/Player/PlaybackEngine/PlayerEngine.swift
- Tests/PlayerTests/EventsTests.swift
- Tests/PlayerTests/Mocks/Common/World/DevelopmentFeatureFlagProvider+Mock.swift
- Tests/PlayerTests/Player/PlaybackEngine/Internal/Events/PlayerEventSenderTests.swift
- Tests/PlayerTests/Player/PlaybackEngine/Internal/PlayerItemTests.swift
- Tests/PlayerTests/Player/PlaybackEngine/PlayerEngineTests.swift
- Tests/PlayerTests/Playlog/PlayLogTests.swift
We have been testing for a while a change in our Player codebase to send events in a more predictable and controllable manner, which will help a lot with tests stability.
Previously, we were sending events in `PlayerItem.deinit` which puts us at the mercy of the autorelease pool cadence in tests. 
We changed this a more than a month ago, and have been testing both code paths in our tests since then without apparent functionality changes.
This PR migrates our internal development flag to the FeatureFlagProvider so we can test this change in production in a safe manner before committing to it.
> Migrate `shouldSendEventsInDeinit` dev flag to production

- Sources/Auth/Network/DefaultLoginService.swift
`client_unique_key` can be `nil` or an `empty string` and as such should not be included as a part of URLQuery items.
> Append `client_unique_key` only if present (iOS-Auth)

- Sources/Player/Common/PlaybackInfo/PlaybackInfoFetcher.swift
- Sources/Player/Configuration.swift
- Tests/PlayerTests/PlaybackInfoFetcherTests.swift
This PR adds a new param `immersiveaudio` to `playbackinfo` endpoint. When set to false and requesting an immersive audio track, a stereo replacement will be served instead.
> Add support for immersiveaudio param in playbackinfo

- Sources/Player/Common/Extensions/AVPlayer.swift
- Sources/Player/Common/Extensions/AVURLAsset.swift
- Sources/Player/Common/Extensions/Player+Extensions.swift
- Sources/Player/Common/FeatureFlags/FeatureFlagProvider+Standard.swift
- Sources/Player/Common/FeatureFlags/FeatureFlagProvider.swift
- Sources/Player/Mocks/Common/FeatureFlags/FeatureFlagProvider+Mock.swift
- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/Legacy/AVPlayerAssetLegacy.swift
- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/Legacy/AVQueuePlayerWrapperLegacy.swift
- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/Legacy/AVURLAssetFactoryLegacy.swift
- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/Legacy/AssetCacheLegacy.swift
- Sources/Player/PlaybackEngine/Internal/Events/StreamingMetrics/StreamingSessionStart/StreamingSessionStart.swift
- Sources/Player/PlaybackEngine/Internal/InternalPlayerLoader.swift
- Sources/Player/PlaybackEngine/Internal/PlayerItem.swift
- Sources/Player/Player.swift
- Tests/PlayerTests/Player/PlaybackEngine/Internal/PlayerItemTests.swift
- Tests/PlayerTests/Playlog/PlayLogTests.swift
This PR adds a new FeatureFlag to control access to the new player caching implementations that will follow in the next PR.
Renames the 3-4 classes for the current AVQueuePlayerWrapper implementation as `ClassNameLegacy` as we have done in previous similar situations. This duplicates code but will allow us to quickly delete the legacy implementation once we have validated the new one in production.
It also adds metrics tracking via a new `SessionTag`. 
All these will allows us to control the deployment of the new code and measure its impact vs the previous implementation.
> Part 1: Feature flag setup for new caching implementation

- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/AVQueuePlayerWrapper.swift
While testing the new caching implementation currently under a FeatureFlag, it was noticed that in some scenarios, there was a 3-4 second buffering that should not be happening.
When the first track in a PlayerEngine instance is loaded, and the track is not offlined or cached, it could lead to the track not starting playback until the full track is downloaded/cached.
The solution is to load into the player queue on the play() command whatever track has been loaded but was being cached.
> Fix long buffering w/ new caching implementation

- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/AVQueuePlayerWrapper.swift
While testing the new caching implementation currently under a FeatureFlag, it was noticed that when killing the app, playback would continue for 3-4 extra seconds instead of stopping automatically.
A change was made to call `player.removeAllItems()` instead of `player.pause()` when unloading/resetting the player.
This is what the documentation for removeAllItems() says
```
/**
@method     removeAllItems
@abstract   Removes all items from the queue.
@discussion Stops playback by the target.
*/
open func removeAllItems()
```
The solution is to call `player.pause()` too as `player.removeAllItems()` is not enough to stop playback, even if the documentation says it should be.
> Fix playback not stopping immediately on reset

- Sources/Player/Common/Extensions/Player+Extensions.swift
- Sources/Player/Mocks/PlaybackEngine/PlayerMock.swift
- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/AVQueuePlayerWrapper.swift
- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/Legacy/AVQueuePlayerWrapperLegacy.swift
- Sources/Player/PlaybackEngine/Internal/InternalPlayerLoader.swift
- Sources/Player/PlaybackEngine/Internal/MediaPlayers/GenericMediaPlayer.swift
- Sources/Player/PlaybackEngine/Internal/MediaPlayers/LiveMediaPlayer.swift
- Sources/Player/PlaybackEngine/Internal/MediaPlayers/UCMediaPlayer.swift
- Sources/Player/PlaybackEngine/Internal/MediaPlayers/VideoPlayer.swift
- Sources/Player/PlaybackEngine/Internal/PlayerLoader.swift
- Tests/PlayerTests/Mocks/PlaybackEngine/Internal/PlayerLoaderMock.swift
Our current `GenericMediaPlayer` interface was being used for both the main internal player and for external players, but some of the functionality in the interface can't be supported from external players.
This was forcing external players to implement the extra method signatures as no-ops.
This PR splits all the related functionality only available to the main player out of the `GenericMediaPlayer` protocol and into their own interfaces, to avoid imposing them on external players that won't need them.
> Splitted GenericMediaPlayer responsibilities

- Sources/Player/Common/World/DevelopmentFeatureFlagProvider/DevelopmentFeatureFlagProvider+Live.swift
- Sources/Player/Common/World/DevelopmentFeatureFlagProvider/DevelopmentFeatureFlagProvider.swift
- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/AVQueuePlayerWrapper.swift
- Sources/Player/PlaybackEngine/Internal/PlayerItem.swift
- Tests/PlayerTests/Mocks/Common/World/DevelopmentFeatureFlagProvider+Mock.swift
A long time ago, we added reading playback metadata from the actual content as a PoC, and later, when we started getting that data from the backend, we decided to use it as an extra verification to make sure both datapoints match.
It also allowed us to give the client the metadata in cases where things had been offlined before this metadata was being used.
Now we are in a position where the backend will always provide the data, and there is no need to backfill old offlined items with it, so this is probably something we should get rid of.
This PR moves all the related functionality behind a Development Feature Flag, which allows us to disable it without removing the code yet and will make it easier later to either add it again or remove it completely.
> Disabled playback metadata assertions

- Sources/EventProducer/Events/Logic/EventScheduler.swift
- Sources/EventProducer/Events/Models/EventConfig.swift
- Sources/EventProducer/Monitoring/Monitoring.swift
- Sources/EventProducer/Outage/OutageState.swift
- Sources/EventProducer/TidalEventSender.swift
- Tests/EventProducerTests/EventsTests/EventsTests.swift
- Tests/EventProducerTests/HelperTests/FileManagerHelperTests.swift
- Tests/EventProducerTests/MonitoringTests/MonitoringTests.swift
- Tests/EventProducerTests/NetworkingTests/NetworkingTests.swift
Currently we only check if a single event is under a certain `maxDiskUsageBytes`, whereas we need to make sure the entire queue is under the pre-defined size, as noted in [🧾 documentation.](https://github.com/tidal-music/tidal-sdk/blob/main/EventProducer.md#queue)
This PR addresses that issue and introduces the default check for a singular event.
> Check Queue Size (iOS)

- Sources/EventProducer/Events/Logic/EventQueue.swift
- Sources/EventProducer/Monitoring/MonitoringQueue.swift
We open database in `EventQueue` (i.e we create an instance of `DatabaseQueue`) if it was not done before. If it is already there, we just return it.
However, if multiple threads try to do it simultaneously, the `if let _dbQueue` is `false` for all of them and thus, we create multiple instances of the database. Since we override `_dbQueue` every time, we assume that at some point we try to call already deallocated instance - and there is a crash
Changing class to actor should solve this data race by providing thread-safe access to `dbQueue` computed property - so we will really have only one instance, and further calls will just return already existing `_dbQueue`
| Before    | After |
| -------- | ------- |
|![Screenshot 2024-07-22 at 17 14 …
> Fix EventQueue.addEvent crash

- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/AVQueuePlayerWrapper.swift
During our staged rollout of the improved cache implementation, a crash was discovered.
The crash happens because, under some circumstances, we are inserting an `AVPlayerItem` in the `AVQueuePlayer` queue that is already there, which is not allowed.
In this PR we protect against this by making sure all `player.insert()` calls are done after a check to `player.canInsert()`
> [Player] Fix crash by ensuring all player insertions are protected by a canInsert() check

- .github/workflows/lint.yml
- .github/workflows/unit-test.yml
It seems our `branches` array in the `pull_request` trigger had a wrong format, which was affecting both `lint` and `unit-test` actions. This PR aims to fix it.
---
This pull request includes changes to the GitHub Actions workflows to improve branch matching for pull requests.
Changes to GitHub Actions workflows:
* [`.github/workflows/lint.yml`](diffhunk://#diff-107e910e9f2ebfb9a741fa10b2aa7100cc1fc4f5f3aca2dfe78b905cbd73c0d2L7-R8): Updated the `pull_request` trigger to match all branches using the `**` wildcard.
* [`.github/workflows/unit-test.yml`](diffhunk://#diff-d4223b44df678cece85f2542c19b9cd060d43b22f753c25214d5942ef2ca5d18L7-R8): Updated the `pull_request` trigger to match all branches using the `**` wildcard.
> fix GH workflow PR trigger in lint.yml and unit-test.yml

- Sources/Auth/Storage/DefaultTokensStore.swift
We have already fixed EP crash here: https://github.com/tidal-music/tidal-sdk-ios/pull/39
But our `DefaultTokensStore` is also not thread-safe and we get similar crashes (related to deallocation of `Tokens`). Supposedly, the reason is the same...
We can't apply the same approach with `actor`, because it requires to make all methods `async`, and methods calling these methods too, etc
> Fix Credentials related crashes

- Sources/Player/PlaybackEngine/PlayerEngine.swift
- Tests/PlayerTests/Player/PlaybackEngine/PlayerEngineTests.swift
In order to fix the playlog tests, we need to address one of the different behaviors observed. So in this PR we address this different behavior - used by new playlog tests coming up in next PRs.
⚠️ The functionality itself (skip to next) is still under testing and therefore under control in case of any issues - the reason why I haven't added a FF.
⚠️ We can only run all player tests in all PRs again after this set of PRs are merged and we fix known existing flakiness.
---
This pull request includes changes to the `PlayerEngine` class in the `PlayerEngine.swift` file to streamline the `skipToNext` method and improve code readability.
Code simplification:
* [`Sources/Player/PlaybackEngine/PlayerEngine.swift`](diffhunk://#diff-e72feb354eac41dcce7baa31a6b2455945960a35c569f3ab640daa0e629a2015L1 …
> Playlog tests: Align skipToNext behavior with Android: don't do anything when there's no nextItem set up

- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/AVPlayerItemErrorLogEvent.swift
In [the previous PR](https://github.com/tidal-music/tidal-sdk-ios/pull/56), I missed adding the available also for mac, so doing it now.
> Add available check for mac in AVPlayerItemErrorLogEvent

- Sources/Common/Extensions/String+Extensions.swift
- Sources/EventProducer/Events/Logic/EventScheduler.swift
- Tests/EventProducerTests/EventsTests/EventsTests.swift
Currently parameter value do not conform to [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986) allowing certain events to fail.
✅ No changes needed on client-side
✅ Verified ingestion
> Add parameter encoding

- Sources/Player/Common/FeatureFlags/FeatureFlagProvider+Standard.swift
- Sources/Player/Common/FeatureFlags/FeatureFlagProvider.swift
- Sources/Player/Mocks/Common/FeatureFlags/FeatureFlagProvider+Mock.swift
This pull request includes changes to the `FeatureFlagProvider` struct and its extensions to remove the `isStallWhenTransitionFromEndedToBufferingEnabled` feature flag. The most important changes involve updating the initialization and usage of `FeatureFlagProvider` in both the main and mock implementations.
Changes to `FeatureFlagProvider`:
* [`Sources/Player/Common/FeatureFlags/FeatureFlagProvider.swift`](diffhunk://#diff-4cd187606f8aae83fb59b73a080a87896fe6033ce7fed43af1bc02b0d4b5dfc5L2-L17): Removed the `isStallWhenTransitionFromEndedToBufferingEnabled` property and its initialization from the `FeatureFlagProvider` struct.
Updates to standard feature flags:
* [`Sources/Player/Common/FeatureFlags/FeatureFlagProvider+Standard.swift`](diffhunk://#diff-357b6e003c6e1c07f64bda0a4006d43ba8928 …
> Remove `isStallWhenTransitionFromEndedToBufferingEnabled` from `FeatureFlagProvider`

- Sources/Player/Common/Types/Interruption.swift
- Sources/Player/Common/Types/MediaProduct.swift
- Sources/Player/Common/Types/StoredMediaProduct.swift
- Sources/Player/Mocks/Common/Types/MediaProduct+Mock.swift
- Sources/Player/Mocks/Common/Types/StoredMediaProduct+Mock.swift
- TestApps/Player/PlayerTestApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
We were missing `referenceId` inside `MediaProduct` from the Player spec.
> Added MediaProduct.referenceId from the Player spec

- .github/workflows/unit-test.yml
Seems like I deleted one line by mistake in this [PR](https://github.com/tidal-music/tidal-sdk-ios/commit/7752931130586d7c8b51c0ae8a08f232e3f0c526). And from there on the trigger release got broken for 3 weeks. 🙀 
---
This pull request includes a small change to the `.github/workflows/unit-test.yml` file. The change adds a `workflow_call` trigger to the unit test workflow.
* [`.github/workflows/unit-test.yml`](diffhunk://#diff-d4223b44df678cece85f2542c19b9cd060d43b22f753c25214d5942ef2ca5d18R4): Added `workflow_call` trigger to the unit test workflow to enable reusability of the workflow in other workflows.
> Update unit-test.yml to fix broken release trigger

- .github/CODEOWNERS
This pull request includes changes to the `.github/CODEOWNERS` file, reorganizing team ownership assignments for various source and test files. The most important changes involve consolidating multiple teams under a single team and updating the ownership structure to reflect this consolidation.
Ownership reorganization:
* Consolidated the `BITS` and `Platform` teams into the `Music Foundations` team. (`.github/CODEOWNERS`)
* Assigned the `Music Foundations` team to the following directories and their respective test directories:
- `Sources/Player/`
- `Sources/Auth/`
- `Sources/Common/`
- `Sources/EventProducer/`
- `Sources/Template/` (`.github/CODEOWNERS`)
> Update ownership removing platform, pace and bits and replacing them with mf

- Sources/Auth/Model/AuthConfig.swift
- Sources/Auth/Model/AuthLoggable.swift
- Sources/Auth/TidalAuth.swift
We're going to set it up (set a log handler) on clients instead, since it is a static property which may be called just once.
Instead, we introduce `isLoggingEnabled`, in case a client doesn't need logging
> Do not set up logging system in auth

- Sources/Player/Mocks/PlaybackEngine/UserConfiguration+Mock.swift
- Sources/Player/PlaybackEngine/Internal/Events/PlayerEventSender.swift
- Sources/Player/PlaybackEngine/Internal/Events/User.swift
- Sources/Player/Player.swift
- Tests/PlayerTests/Mocks/PlaybackEngine/Internal/Events/PlayerEventSenderMock.swift
- Tests/PlayerTests/Player/PlaybackEngine/Internal/Events/PlayerEventSenderTests.swift
- Tests/PlayerTests/Player/PlaybackEngine/Internal/PlayerItemTests.swift
- Tests/PlayerTests/Player/PlayerTests.swift
- The user id is now fetched from the auth's `CredentialsProvider`. 
- The user client id is now supplied through a function block. 
- User's clientId is now made nullable.
> Removing setupUserConfiguration from Player

- .github/workflows/unit-test.yml
We are getting false positives in unit tests (even if they don't build). As pointed out by Alberto, we were missing a command to actually fail with proper exit status.
> Update unit test action

- Sources/Player/PlaybackEngine/Internal/Events/StreamingMetrics/PlaybackStatistics.swift
- Sources/Player/PlaybackEngine/Internal/Metadata.swift
- Sources/Player/PlaybackEngine/Internal/PlaybackSource.swift
- Sources/Player/PlaybackEngine/Internal/PlayerItem.swift
- Sources/Player/PlaybackEngine/Internal/PlayerItemLoader.swift
- Tests/PlayerTests/Mocks/PlaybackEngine/Internal/Events/StreamingMetrics/PlaybackStatistics+Mock.swift
- Tests/PlayerTests/Mocks/PlaybackEngine/Internal/Metadata+Mock.swift
We needed a way to differentiate plays coming from our new offliner implementations vs the legacy ones we are substituting, to track the health of the new feature during the rollout..
For that, I added a tag in the `PlaybackStatistics` event when the playback is coming from an object stored in the new offliner format.
> [Player] StreamingMetrics support for new offliner

- Sources/Common/Extensions/String+Extensions.swift
- Sources/Player/Common/Authentication/CredentialsSuccessDataParser.swift
- Tests/PlayerTests/Player/Common/Authentication/CredentialsSuccessDataParserTests.swift
Current the client id can result to null if the string is not a perfect base 64 encoded string. This PR fixes this issue.
> Fix parsing error in clientIdFromToken

- Package.swift
- Sources/Common/Logger/TidalLogger.swift
Per discussions, it makes more sense to keep `#fileID` instead of `#file` as the default for the file in logging. 
---
This pull request includes a small but important change to the `TidalLogger` class in the `Sources/Common/Logger/TidalLogger.swift` file. The change updates the `log` method to use `#fileID` instead of `#file` for the `file` parameter.
* [`Sources/Common/Logger/TidalLogger.swift`](diffhunk://#diff-2aa1cc4116b0d5e2839fc86b7bc79f401500a84389d631342411376a3fe26e6dL20-R20): Updated the `log` method to use `#fileID` instead of `#file` for the `file` parameter.
> Add Common product, replace #file with #fileID in logging

- Sources/Player/Common/Logging/PlayerLoggable.swift
- Sources/Player/Common/Utils/FileManager/FileManagerClient+Live.swift
- Sources/Player/Common/Utils/FileManager/FileManagerClient.swift
- Sources/Player/OfflineEngine/Internal/Storage/GRDBStorage/GRDBOfflineStorage.swift
- Sources/Player/PlaybackEngine/Internal/PlayerItemLoader.swift
- Sources/Player/PlaybackEngine/PlayerEngine.swift
- Sources/Player/Player.swift
- Tests/PlayerTests/Mocks/Common/Utils/FileManager/FileManagerClient+Mock.swift
- Tests/PlayerTests/Player/OfflineEngine/Internal/Storage/DBStorage/GRDBOfflineStorageTests.swift
While `OfflineEngine` is still under a development flag, both `OfflineEngine` and `OfflineStorage` should be optional, and the lack of any should not affect Player functionality.
This way we isolate better any possible issues with the new code.
I've also improved the database initialization for the `OfflineStorage` layer, by creating it in the Application Support directory, which follows the platform's recommended suggestions, and the database is inside a specific folder, making it easy to remove it or move it in the future, as the SQLite database creates multiple files for it.
> [Player] Better OfflineStorage and OfflineEngine initialization

- Sources/Auth/Storage/DefaultTokensStore.swift
- Sources/Common/Extensions/Dictionary+Extensions.swift
- Sources/Common/Extensions/String+Extensions.swift
- Sources/EventProducer/Monitoring/Monitoring.swift
- Sources/Player/Common/Authentication/CredentialsSuccessDataParser.swift
- Sources/Player/PlaybackEngine/Internal/Events/PlayerEventSender.swift
- Sources/Player/PlaybackEngine/Internal/StreamingPrivileges/StreamingPrivilegesHandler.swift
- Tests/PlayerTests/Playlog/PlayLogTests.swift
- Tests/PlayerTests/Playlog/PlayLogTestsWithDeinit.swift
As the title says.
[One of the warnings](https://realm.github.io/SwiftLint/non_optional_string_data_conversion.html) was related to how we were doing Data <-> String conversions, because if we use UTF8 encoding, it can never fail, so we can change to a non-optional way of doing it.
[More info here](https://github.com/realm/SwiftLint/issues/5263) and [here](https://www.swiftbysundell.com/tips/converting-between-string-and-data-without-optionals/)
> Removed recent SwiftLint warnings

- Sources/Common/Logger/LoggerMetadata+Extension.swift
- Sources/Common/Logger/TidalLogger.swift
There is no need to create `TidalLoggable` in simple scenarios.
This function allows to log without it.
Also, I made a `source` mandatory
> Simple logging API

- Sources/Auth/Model/AuthLoggable.swift
- Sources/Common/TidalError.swift
Do not use localized description for errors. Instead, use `String(describing:)` and `CustomStringConvertible`
> Better error descriptions

- Sources/Player/Common/FeatureFlags/FeatureFlagProvider+Standard.swift
- Sources/Player/Common/FeatureFlags/FeatureFlagProvider.swift
- Sources/Player/Mocks/Common/FeatureFlags/FeatureFlagProvider+Mock.swift
- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/AVQueuePlayerWrapper.swift
- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/Legacy/AVQueuePlayerWrapperLegacy.swift
Attempt to address an issue we have around seeking.
⚠️ I'm testing our metrics to make sure nothing gets broken because of this, so the code is not final. Also, because our playlog tests are flaky, we cannot fully rely on them, so I'm adapting and testing locally since they are less flaky than in CI.
---
This pull request introduces a new feature flag for pausing and playing around seek operations in the player, along with the necessary logic to handle this behavior in the `AVQueuePlayerWrapper` and `AVQueuePlayerWrapperLegacy` classes. The most important changes are as follows:
* [`Sources/Player/Common/FeatureFlags/FeatureFlagProvider.swift`](diffhunk://#diff-4cd187606f8aae83fb59b73a080a87896fe6033ce7fed43af1bc02b0d4b5dfc5R6-R19): Added `shouldPauseAndPlayAroundSeek` to the …
> As an attempt to fix a seek issue, add a FF which means we will pause and play around the seek call

- Sources/Player/Common/Logging/PlayerLoggable.swift
- Sources/Player/Common/Utils/FileManager/FileManagerClient+Live.swift
- Sources/Player/Common/Utils/FileManager/FileManagerClient.swift
- Sources/Player/OfflineEngine/Internal/DownloadTask.swift
- Sources/Player/OfflineEngine/Internal/MediaDownloader.swift
- Tests/PlayerTests/Mocks/Common/Utils/FileManager/FileManagerClient+Mock.swift
As part of the new `OfflineEngine`, we want to calculate the total size of the downloaded Media so we can expose it to our users.
This PRs adds functionality to calculate both the size of progressive files downloaded, as well as the size of HLS streams downloaded.
HLS streams are stored as a folder with a bunch of files and subfolders, and we need to calculate the total size of all of those files.
> [Player] Calculate size of downloaded MediaProducts

- Sources/Player/Common/Logging/PlayerLoggable.swift
- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/AVQueuePlayerWrapper.swift
- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/AVURLAssetFactory.swift
Adjusted the implementation of `AVQueuePlayerWrapper` that uses the improved caching system to solve a crash we have seen on production when we enable the flag to a % of our users.
Unfortunately, we have been unable to reproduce this crash locally.
We have been testing for the past few days a build using this PR branch with ~20 users and ~4k streams without the crash happening and without other issues appearing.
This PR contains two main changes to the Player <-> cache integration
* The cache uses it's own queue
* We enqueue immediately the first item we load even if it's not cached, instead of waiting until the play is called (this was done to have more time to start caching it)
> [PLAYER] Reworked AVQueuePlayerWrapper to solve enqueue crash

- Package.swift
- Sources/Common/AnyCodableDictionary.swift
- Sources/Player/Common/Types/MediaProduct.swift
- Sources/Player/Common/Types/MediaProductExtras.swift
- Sources/Player/Common/Types/StoredMediaProduct.swift
- Sources/Player/Mocks/Common/Types/MediaProduct+Mock.swift
- Sources/Player/Mocks/Common/Types/StoredMediaProduct+Mock.swift
- Sources/Player/PlaybackEngine/Internal/Events/LegacyEvent.swift
- Sources/Player/PlaybackEngine/Internal/Events/PlayerEvent.swift
- Sources/Player/PlaybackEngine/Internal/Events/PlayerEventSender.swift
- Tests/CommonTests/AnyCodableDictionaryConversionTests.swift
- Tests/CommonTests/CommonTests.swift
- Tests/PlayerTests/Mocks/PlaybackEngine/Internal/Events/PlayerEventExtrasMock.swift
- Tests/PlayerTests/Mocks/PlaybackEngine/Internal/Events/PlayerEventSenderMock.swift
- Tests/PlayerTests/Player/PlaybackEngine/Internal/Events/PlayerEventSenderTests.swift
This PR aims to introduce `AnyCodable` extras for the `MediaProduct` class, which will allow any aCodablea object from the client app to be passed as `extras`. 
- The [`AnyCodable`](https://github.com/Flight-School/AnyCodable) library was recently added to this project as part of the OpenAPI work being done. This simplified this piece of work quite a bit, as this library is exactly the solution that was proposed for this solution. 
- A new type (typealias for now) `AnyCodableDictionary = [String: AnyCodable?]` was introduced in the `Common` module. This was done to prevent the undesired spread of the `AnyCodable` type to the `Player` module. By doing this, the `Player` doesn't require new explicit dependencies at least. 
- In addition all `Encodable` types were extended with a …
> AnyCodable Extras

- Package.swift
To enable using the contents of `Common` individually it needs to be exposed as a product
> Add `Common` product

- Sources/Player/Common/Logging/PlayerLoggable.swift
- Sources/Player/OfflineEngine/Internal/DownloadTask.swift
- Sources/Player/OfflineEngine/Internal/MediaDownloader.swift
- Sources/Player/OfflineEngine/OfflineEngine.swift
I noticed a couple of bugs in the size calculation code while testing the client integration.
This PR fixes them, and refactors the size calculation into the `DownloadTask` , where it makes more sense.
The two things fixed:
* Use the correct size algorithm for the calculation based on the download type (using PlaybackInfo), 
* Use the final URL where we move the progressive file download into, instead of the temporary download path! 🤦‍♂️
> [Player] Fix OfflineItem size calculation

- Sources/Player/OfflineEngine/OfflineEngine.swift
Reworked the delete entry logic to cover edge cases where the media file or the license file are not available.
> [Player] Fix OfflineEntry deletion edge cases

- Sources/Player/Common/Event/NotificationsHandler.swift
- Sources/Player/Mocks/OfflineEngine/OfflineEngineListenerMock.swift
- Sources/Player/OfflineEngine/OfflineEngine.swift
- Sources/Player/OfflineEngine/OfflineEngineListener.swift
- Sources/Player/Player.swift
- TestApps/Player/PlayerTestApp/PlayerViewModel.swift
- Tests/PlayerTests/EventsTests.swift
- Tests/PlayerTests/FeatureFlagProviderTests.swift
- Tests/PlayerTests/Mocks/Common/NotificationHandler/NotificationsHandler+Mock.swift
- Tests/PlayerTests/Mocks/Player+Mock.swift
- Tests/PlayerTests/Player/PlaybackEngine/PlayerEngineTests.swift
- Tests/PlayerTests/PlayerStateTests.swift
Refactored and renamed `OfflinerDelegate` into `OfflineEngineListener`, and added it to the bootstrap process.
Now it also ensures it will use the same queue for the notification events as the `PlayerListener`
One possibility to discuss would be to have different queues for each listener and instead of using `NotificationsHandler` for both, have a different class for each.
> [Player] Refactor OfflineEngine Listener setup and handling

- Sources/Player/OfflineEngine/Internal/DownloadTask.swift
- Sources/Player/OfflineEngine/Internal/LicenseDownloader.swift
- Sources/Player/OfflineEngine/Internal/Storage/GRDBStorage/GRDBOfflineStorage.swift
- Sources/Player/OfflineEngine/Internal/Storage/GRDBStorage/OfflineEntryGRDBEntity.swift
- Sources/Player/OfflineEngine/Internal/Storage/OfflineEntry.swift
- Tests/PlayerTests/Mocks/OfflineEngine/Internal/Storage/OfflineEntry+Mock.swift
There were some edge cases not controlled properly due to the fact that not all products require a license.
In this PR I make sure that we only enforce the existence of a license file if the product needs it, deletion will not fail if a license fail is missing, and I also move the license files to a better path that will not be cleared by the OS.
> [Player] Improved License handling in OfflineEngine

- Sources/Player/OfflineEngine/Internal/MediaDownloader.swift
- Sources/Player/OfflineEngine/Internal/Storage/GRDBStorage/GRDBOfflineStorage.swift
Change the naming of the downloaded HLS AVURLAssets to match the naming used in the cache.
This naming will better reflect what is actually stored in case a user navigates to the Storage settings on their device.
At some later point, we might decide to bridge the user-facing name of the MediaProduct (and the artwork!), which we could use here.
> [Player] Rename HLS assets in OfflineEngine

- Sources/Player/Common/FeatureFlags/FeatureFlagProvider+Standard.swift
- Sources/Player/Common/FeatureFlags/FeatureFlagProvider.swift
- Sources/Player/Mocks/Common/FeatureFlags/FeatureFlagProvider+Mock.swift
- Sources/Player/Player.swift
- Tests/PlayerTests/FeatureFlagProviderTests.swift
- Tests/PlayerTests/Mocks/OfflineEngine/Internal/Downloader+Mock.swift
- Tests/PlayerTests/Mocks/OfflineEngine/OfflineEngine+Mock.swift
- Tests/PlayerTests/Player/PlayerTests.swift
Now that we are getting ready to test the new Offline Engine, we need to have it always initialized because there can be cases where someone downloads stuff with it, but then it gets the FF flag disabled for it, and it needs to still be able to play them.
> [Player] Make OfflineEngine non-optional

- Sources/Player/Common/PlaybackInfo/PlaybackInfoFetcher.swift
- Sources/Player/OfflineEngine/Internal/Downloader.swift
- Sources/Player/OfflineEngine/OfflineEngine.swift
- Sources/Player/Player.swift
We had a silly bug inside `OfflineEngine`
We are using a struct for the configuration type instead of a class, so when we pass it around, it is a copy, not a reference.
When the quality is changed by the client, we are not updating the configuration object in the `OfflineEngine`
> [Player] Update configuration object inside OfflineEngine

- Sources/Player/PlaybackEngine/Internal/PlaybackSource.swift
- Sources/Player/PlaybackEngine/Internal/PlayerItem.swift
As the title says, we would also like to send `OfflinePlay` events for items downloaded with the new `OfflineEngine`
> [Player] Support OfflinePlay event in OfflineEngine items

- Sources/Player/Mocks/PlaybackEngine/PlayerMock.swift
- Sources/Player/OfflineEngine/Internal/Storage/PlayableOfflinedMediaProduct.swift
- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/AVQueuePlayerWrapper.swift
- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/Legacy/AVQueuePlayerWrapperLegacy.swift
- Sources/Player/PlaybackEngine/Internal/InternalPlayerLoader.swift
Although the functionality was working correctly, it was by luck. We had a sily mistake where we weren't properly identifying `PlayableOfflinedMediaProduct` plays comming from our OfflineEngine as `offlined`, so the check we were doing inside `AVQueuePlayerWrapper.canPlay()` was incorrect once that was fixed.
This PR solves both issues:
* Correctly identify `PlayableOfflinedMediaProduct` plays as `isOfflined: true`
* Change the check for `FLAC` files to use the `MediaType` of the file to decide if it can be played or not
> [Player] Fix AVQueuePlayerWrapper.canPlay() for PlayableOfflinedMediaProduct 

- Sources/Player/Player.swift
- Tests/PlayerTests/Player/PlayerTests.swift
Their PR changes how external players are provided so they can be changed at runtime.
Currently, we were passing an array at `bootstrap` that can't be updated, and this caused issues with our improved caching feature flag.
> [Player] Improve external player injection

- .github/workflows/generate-tidal-api.yml
This is the CI/CD workflow for checking if there are API changes. For now will be triggered manually, we will setup a schedule in phase 2.
How it works:
* Checkout code
* Install OpenAPI Generator via Homebrew
* Then we run our [code generation script](https://github.com/tidal-music/tidal-sdk-ios/blob/main/Sources/TidalAPI/generate_and_clean.sh). The script fetches latest JSON input files, places them to the input folder (`Config/input`) and runs the generator. The generator then will re-generate all the APIs and models based on the input files and place the result to the output folder (`Generated`)
* Check for changes in these folders. 
* Here we use `git status -s`, which provides lines containing a prefix (`A`, `M` or `D`) and a file name. 
* We also remove double quotes (`sed …
> TidalAPI: setup CI/CD (phase 1)

- .github/workflows/generate-tidal-api.yml
Adjusted title and commit message of a PR created by GitHub Actions: included there calculated changed file count (changes in the Input folder + changes in the Generated folder)
This is how the Pull Request looks now: https://github.com/tidal-music/tidal-sdk-ios/pull/154 (it is opened against my test branch)
> TidalAPI - CI/CD follow up (better PR title and commit message)

- Sources/Player/Common/World/DevelopmentFeatureFlagProvider/DevelopmentFeatureFlagProvider+Live.swift
- Sources/Player/Common/World/DevelopmentFeatureFlagProvider/DevelopmentFeatureFlagProvider.swift
- Sources/Player/OfflineEngine/Internal/Storage/OfflineEntry.swift
- Tests/PlayerTests/Mocks/Common/Types/PlaybackInfo+Mock.swift
- Tests/PlayerTests/Mocks/Common/World/DevelopmentFeatureFlagProvider+Mock.swift
- Tests/PlayerTests/Player/OfflineEngine/Internal/Storage/OfflineEntryTests.swift
- Tests/PlayerTests/Player/PlaybackEngine/Internal/InternalPlayerLoaderTests.swift
- Tests/PlayerTests/Player/PlaybackEngine/Internal/Utils/LoudnessNormalizerTests.swift
Moved the expiry check behind a development flag so we can work on a full revalidation implementation and improved UTs
> [Player] Fix logic for OfflineEntry state check 

- Sources/Player/Common/Errors/ErrorId.swift
- Sources/Player/Common/Errors/PlayerInternalError.swift
- Sources/Player/PlaybackEngine/Internal/PlayerItemLoader.swift
- Sources/Player/PlaybackEngine/Internal/PlayerItemLoaderError.swift
- Sources/Player/PlaybackEngine/PlayerEngine.swift
- Sources/Player/Player.swift
- Tests/PlayerTests/Mocks/Player+Mock.swift
We want to be able to check inside `PlaybackEngine` if the user has permissions to play an offlined track.
> [Player] Add OfflinePrivilegeCheck to bootstrap process

- Sources/Auth/Model/AuthLoggable.swift
For more convenient auth log error handling on clients, I decided to add an event code in metadata
> AuthLoggable: added event code in metadata

- Sources/Auth/Model/AuthLoggable.swift
- Sources/Common/Logger/LoggerMetadata+Extension.swift
- Sources/Player/Common/Logging/PlayerLoggable.swift
For the sake of consistency, I decided to extract most common metadata keys to its extension. These keys can also be used on clients
> Logging: Unify common metadata keys

- Sources/Auth/Model/AuthLoggable.swift
For some cases code was not set, because we returned from the function before 😅 
It's a pity that I discovered it right after releasing a new version...
> AuthLoggable - fix AuthLoggable metadata

- Sources/Player/Common/Logging/PlayerLoggable.swift
- Sources/Player/Common/Utils/FileManager/FileManagerClient+Live.swift
- Sources/Player/Common/Utils/FileManager/FileManagerClient.swift
- Sources/Player/OfflineEngine/Internal/Storage/GRDBStorage/GRDBOfflineStorage.swift
- Sources/Player/Player.swift
- Tests/PlayerTests/Mocks/Common/Utils/FileManager/FileManagerClient+Mock.swift
We noticed some crashes in our TIDAL client happening under some circumstances, which were caused due to an uninitialized Player instance.
After some investigation, the reason why the Player was not being initialised properly was due to an error opening the `OfflineStorage` database.
We are already logging when this happens, unfortunately, this was happening before we had initialized the `PlayerLogger` 😅 
If we had the logs in place, we probably would see that the issue is due to the db file having `fileProtection = .completeFileProtectionUntilFirstUserAuthentication`. When the app gets prewarmed after a reboot, but before the user has unlocked his device for the first time, this files are not accesible, and `Player.bootstrap()` will fail, causing a crash in our client because it expects …
> [Player] Fix initialization errors due to file Protection in OfflineStorage DB

- Sources/Player/PlaybackEngine/Internal/AVQueuePlayer/AVQueuePlayerWrapper.swift
With the new `Player` implementations used after the Caching v2 project, we disabled behind a development flag the feature of reading the asset metadata.
Unfortunately, we forgot to report the asset metadata provided by the backend instead, which resulted in the `AVAudioSession` output sample rate not being updated as the user switches tracks.
Report output sample rate from BE even if we are not verifying it from the asset
> [Player] Fix output sample rate (mainly for DACs)

- Package.resolved
- Package.swift
We are moving the lint to pre-commit. In this PR, I simply remove the SwiftLint plug-in.
> Remove swiftlint plugin

- Sources/TidalAPI/Utils/RequestHelper.swift
Currently the `RequestHelper` checks for a few conditions before making requests. One of the check is whether the user is logged in. It throws an error if that's not the case. This limits the TidalAPI to be only used when the user is authenticated. 
This prevents its usage with Client Credentials auth flow where the client is authenticated and capable to make API requests that don't require user authentication. This PR removes the check of `isUserLoggedIn == true`.
> Remove isUserLoggedIn check in TidalApi

- .github/workflows/lint.yml
Over the weekend, there was a security issue with the tj-actions/changed-file action that we use in the lint workflow.
This PR removes the need of having an external dependency for this simple use case.
> Changed linter action to resolve security issue

- .github/workflows/lint.yml
Previously [I made a fix](https://github.com/tidal-music/tidal-sdk-ios/commit/03e445517974f9e73260df117835b76f17639599) because the lint workflow was failing in every PR.
Unfortunately, this fix did not work for merge queues, so [we still have errors on the CI](https://github.com/tidal-music/tidal-sdk-ios/actions/runs/14199968044?pr=197) for those cases.
This PR fixes that.
> [CI] Modify lint workflow to support merge queues

- .github/workflows/lint.yml
Unfortunately, there is no way to test the merge queue before merging the PR.
Last attempt failed with this error
```
fatal: bad revision 'origin/refs/heads/main'
```
So I have updated the script to remove `refs/head`
> Attempt 3 at fixing the linter step in a merge queue

- .github/workflows/lint.yml
- Sources/TidalAPI/Config/custom_template/modelOneOf.mustache
- Sources/TidalAPI/generate_and_clean.sh
* Fix the `modelOneOf` custom template to properly support discriminators in the schema
* Improved the generator script with a new cli option `--skip-download` so we can regenerate the code from a local schema (without redownloading the schema from the server)
> OpenAPI generator improvements

- .github/actions/check-api-pr/action.yml
- .github/workflows/check-tidalapi-spec.yml
- .github/workflows/generate-tidal-api.yml
- Sources/TidalAPI/generate_and_clean.sh
This adds 
- Daily automatic checks for the Api spec changes.
- Reuse of already downloaded spec file to avoid double work
- Update of already open PRs created by this workflow
- Generator script now can take a local file as na argument instead of pointing to a fixed location
* Check daily for API updates (edbdacd)
* Update existing PR if needed (5b015c2)
* Use already downloaded spec file on CI (23dd5fb)
> Daily check for tidalapi updates

- .github/workflows/check-tidalapi-spec.yml
- .github/workflows/generate-tidal-api.yml
If we're in the workflow generating new code, we already know there are changes. So there's no ned to later double-check (In addition, the check was faulty, too).
I also improved the PR description a bit, now also adding the spec version the code was generated from.
> Remove unnecessary double branch comparison

- .github/workflows/lint.yml
- Fixes CI linting workflow to properly exclude Generated files
- Removes `-i` flag from SwiftLint execution in CI to respect `.swiftlint.yml` exclusion rules
The CI lint workflow was failing when Generated files were modified because:
1. CI collected all modified Swift files (including those in `Sources/TidalAPI/Generated/`)
2. Used `./bin/swiftlint/run-swiftlint.sh -i` to explicitly lint those files
3. The `-i` flag overrides exclusion rules in `.swiftlint.yml`, causing Generated files to be linted despite being excluded
- Remove the `-i` flag and file list from SwiftLint execution
- Let SwiftLint run normally and respect the exclusion patterns in `.swiftlint.yml`
- Still check if Swift files were modified to avoid unnecessary CI runs
This ensures consistent linting behavior between …
> Fix CI linting to respect .swiftlint.yml exclusion rules

- Sources/Auth/Utils/Utils.swift
When transient failures occur (outages, network blips) or access-token TTL is short, many clients retry at the same intervals. This causes synchronized spikes (thundering herds) and makes recovery slower. Jitter spreads retries over time to smooth load.
- Add bounded jitter (+/-20%) to the retry backoff delay used by `retryWithPolicy(...)`.
- Keeps the number of retries and the nominal backoff progression unchanged; only the per-attempt sleep duration is randomized within a small window.
- `Sources/Auth/Utils/Utils.swift`: `sleep(currentDelay:)` now computes a random delay in `[0.8x, 1.2x]` around the current delay.
- Reduces synchronized load on token endpoints during transient incidents.
- Improves tail latencies and chances of success for clients spread over time.
- No functional …
> Auth: Add jitter to retry delays (+/-20%)
